config/routes.rb
Rails.application.routes.draw do
  get 'images/destroy'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :images, only: [:destroy]
  resources :users, controller: "users" do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "static#index"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  resources :listings do
    resources :reservations, only: [:create]
  end
  resources :reservations, only: [:destroy] do
    resources :braintree, only: [:new, :create]
  end

  get "/my_listings" => "listings#mylisting"
  get '/search', to: 'listings#search', as: 'search'

end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_many :images, dependent: :destroy
  has_many :reservations, dependent: :destroy
  # mount_uploaders :images, ImageUploader
  searchkick match: :word_start, searchable: [:country, :state, :city, :zipcode, :address, :description]
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :update, :edit, :destroy]
  before_action :require_login
  before_action :non_user_only, only: [:index]
  before_action :authorize_check, only: [:update, :destroy, :edit]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all.order('created_at DESC').paginate(:page => params[:page]).per_page(20)
  end

  def search
    @listings = Listing.search(params[:term], fields: ["country", "state", "city", "zipcode", "address", "description"], misspellings: {below: 5}).paginate(:page => params[:page]).per_page(20)
    if @listings.blank?
      redirect_to root_path, flash:{danger: "no successful search result"}
    else
      render :search
    end
  end

  def mylisting
    @listings = current_user.listings
    render 'index'
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    # @reservation = @listing.reservations.new
    # @errors = @reservation.errors.full_messages

  end

  # GET /listings/new
  def new
    @listing = Listing.new
    @image = @listing.images.build
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = current_user.listings.new(listing_params)

    respond_to do |format|
      if @listing.save
        if params[:images]
          params[:images].each do |image|
            @listing.images.create(image: image)
          end
        end

        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        if params[:images]
          @listing.images.destroy_all
          params[:images].each do |image|
            @listing.images.create(image: image)
          end
        end

        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    def authorize_check
      unless @listing.user == current_user || current_user.moderator? || current_user.superadmin?
        redirect_to root_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:place_type, :property_type, :room_number, :bed_number, :guest_number, :country, :state, :city, :zipcode, :address, :price_per_night, :description, images_attributes: [:image, :listing_id])
    end

    def non_user_only
      redirect_to sign_in_path if current_user.user?
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<div class="container">
<%= form_for(listing, :html => { multipart: true }) do |f| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :place_type %>
    <%= f.text_field :place_type %>
  </div>

  <div class="field">
    <%= f.label :property_type %>
    <%= f.text_field :property_type %>
  </div>

  <div class="field">
    <%= f.label :room_number %>
    <%= f.number_field :room_number %>
  </div>

  <div class="field">
    <%= f.label :bed_number %>
    <%= f.number_field :bed_number %>
  </div>

  <div class="field">
    <%= f.label :guest_number %>
    <%= f.number_field :guest_number %>
  </div>

  <div class="field">
    <%= f.label :country %>
    <%= f.text_field :country %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :zipcode %>
    <%= f.number_field :zipcode %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :price_per_night %>
    <%= f.number_field :price_per_night %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
<br>

<%= f.fields_for :image do |ff| %>
    <div class="field" id='uploadavatar'>
      <%= ff.label :image %><br>
      <%= ff.file_field :image, multiple: true, name: "images[]" %>
    </div>
  <% end %>
<br>
<br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

</div>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<h1>Listings</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Place type</th>
      <th>Property type</th>
      <th>Room number</th>
      <th>Bed number</th>
      <th>Guest number</th>
      <th>Country</th>
      <th>State</th>
      <th>City</th>
      <th>Zipcode</th>
      <th>Address</th>
      <th>Price per night</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.user.name %></td>
        <td><%= listing.place_type %></td>
        <td><%= listing.property_type %></td>
        <td><%= listing.room_number %></td>
        <td><%= listing.bed_number %></td>
        <td><%= listing.guest_number %></td>
        <td><%= listing.country %></td>
        <td><%= listing.state %></td>
        <td><%= listing.city %></td>
        <td><%= listing.zipcode %></td>
        <td><%= listing.address %></td>
        <td><%= listing.price_per_night %></td>
        <td><%= listing.description %></td>
        <td><%= link_to 'Show', listing %></td>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listing', new_listing_path %> |
<%= link_to 'My Listings', my_listings_path %>
<br>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path %> |

<%= link_to 'My Listings', my_listings_path %>

app/views/listings/search.html.erb
<h1>Search Results:</h1>
<br>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <% @listings.each do |listing| %>
    <div class="responsive">
      <div class="gallery">
        <%= link_to image_tag(listing.images.first.image.thumb.url), listing%>
        <div class="desc">RM<%= listing.price_per_night %> <%= listing.description %> <%= listing.place_type %></div>
      </div>
    </div>
   <% end %>
  </div>
</div>
<%= will_paginate @listings %>

app/views/listings/show.html.erb
<% if @errors.present? %>
<p><% @errors.each do |x| %>
  <%= x %>
    <% end %>
</p>
<%end%>
<div class="row">
  <div class="col-md-offset-3 col-md-6">
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner">
        <% @listing.images.each_with_index do |i, ind| %>
          <% if ind == 0 %>
            <div class="item active">
              <%= image_tag i.image.url, style:"width: 100%" %>
              <div class="carousel-caption">
                <!-- <h4>Bob</h4> -->
              </div>
            </div>
          <% else %>
            <div class="item">
              <%= image_tag i.image.url, style:"width: 100%" %>
              <div class="carousel-caption">
                <!-- <h4>Alice</h4> -->
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
      <!-- Left and right controls -->
      <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
</div>

<br>

<p>
  <%= image_tag(@listing.user.avatar.thumb.url, :class =>'img-circle') %>
  <strong>User:</strong>
  <%= @listing.user.name %>
</p>

<p>
  <strong>Place type:</strong>
  <%= @listing.place_type %>
</p>

<p>
  <strong>Property type:</strong>
  <%= @listing.property_type %>
</p>

<p>
  <strong>Room number:</strong>
  <%= @listing.room_number %>
</p>

<p>
  <strong>Bed number:</strong>
  <%= @listing.bed_number %>
</p>

<p>
  <strong>Guest number:</strong>
  <%= @listing.guest_number %>
</p>

<p>
  <strong>Country:</strong>
  <%= @listing.country %>
</p>

<p>
  <strong>State:</strong>
  <%= @listing.state %>
</p>

<p>
  <strong>City:</strong>
  <%= @listing.city %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @listing.zipcode %>
</p>

<p>
  <strong>Address:</strong>
  <%= @listing.address %>
</p>

<p id="ppn">
  <strong>Price per night:</strong>
  <%= @listing.price_per_night%>
</p>

<p>
  <strong>Description:</strong>
  <%= @listing.description %>
</p>

<br><br>
<% if @listing.user_id != current_user.id %>
				<!-- Reservation form -->
<%= render 'reservations/form' %>
<% else %>
<h3>Reservations:</h3>
<br>
<table>
  <tr>
    <th>User Name</th>
    <th>Check In</th>
    <th>Check Out</th>
    <th>Number Of Guests</th>
    <th>Total Price</th>
    <th>Paid?</th>
    <th></th>
  </tr>
  <% @listing.reservations.each do |reservation| %>
  <tr>

  <td><%= reservation.user.name %></td>
  <td><%= reservation.check_in.strftime('%d %B %Y') %></td>
  <td><%= reservation.check_out.strftime('%d %B %Y') %></td>
  <td><%= reservation.num_of_guests %></td>
  <td><%= reservation.total_price %></td>
  <td><%= reservation.paid %></td>
  <td><%= link_to "Cancel Reservation", reservation, method: :delete %></td>
  </tr>
<% end %>
</table>
<% end %>

<br>

<% if @listing.user_id == current_user.id %>
  <%= link_to 'Edit', edit_listing_path(@listing) %> |
  <%= link_to 'Back', root_path %>
<% else %>
  <%= link_to 'Back', root_path %>
<% end %>