config/routes.rb
Rails.application.routes.draw do
  get 'images/destroy'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :images, only: [:destroy]
  resources :users, controller: "users" do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "static#index"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  resources :listings do
    resources :reservations, only: [:create]
  end
  resources :reservations, only: [:destroy] do
    resources :braintree, only: [:new, :create]
  end

  get "/my_listings" => "listings#mylisting"
  get '/search', to: 'listings#search', as: 'search'

end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  has_many :authentications, :dependent => :destroy
  has_many :listings, :dependent => :destroy
  has_many :reservations, dependent: :destroy
  enum role: [:user, :moderator, :superadmin]
  after_initialize :set_default_role, :if => :new_record?
  mount_uploader :avatar, AvatarUploader

  def self.create_with_auth_and_hash(authentication, auth_hash)
    user = User.create!(name: auth_hash["extra"]["raw_info"]["name"], email: auth_hash["extra"]["raw_info"]["email"], password: SecureRandom.hex(4))
    user.authentications << (authentication)
    return user
  end

  def fb_token
    x = self.authentications.where(:provider => :facebook).first
    return x.token unless x.nil?
  end

  def set_default_role
    self.role = :user
  end

end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_login, only: [:show, :edit, :update, :destroy, :index]
  before_action :superadmin_only, only: [:index]
  before_action :authorize_check, only: [:update, :destroy]

    def new
        @user = User.new  # = user_from_params
        # render template: "users/new"
    end

    def create
        @user = User.new(user_params)
        if @user.save
            sign_in @user
            redirect_back_or url_after_create
        else
            render template: "users/new"
        end
    end

    def index
      @users = User.all
    end

    def edit
    end

    def show
      @reservation = current_user.reservations
      # unless current_user.superadmin
        # redirect_to root_path
      # end
    end

    def update
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /listings/1
    # DELETE /listings/1.json
    def destroy
      @user.destroy
      respond_to do |format|
        format.html { redirect_to users_url, notice: 'User was successfully deleted.' }
        format.json { head :no_content }
      end
    end

    private
    def set_user
      @user = User.find(params[:id])
    end

    def authorize_check
      if @user != current_user && !current_user.superadmin?
        redirect_to root_path
      end
    end

    def user_params
        params.require(:user).permit(:name, :age, :country, :gender, :email, :password, :avatar)
    end

    def superadmin_only
      redirect_to sign_in_path unless current_user.superadmin?
    end

end

app/views/users/_form.html.erb
<br><br><br>
<div class="row">
      <div class="col-sm-6 col-sm-offset-3 r-form-1-box wow fadeInUp">
        <div class="r-form-1-top">
          <div class="r-form-1-top-left">
            <h1 id="signup2">Sign up now!</h1>
          </div>
          <div class="r-form-1-top-right">
            <i class="fa fa-pencil"></i>
          </div>
        </div>
        <div class="r-form-1-bottom">
            <div class="form-group">
              <%= form.label :name, class:"sr-only" %>
              <%= form.text_field :name, type: 'name', placeholder:"Name...", class:"r-form-1-name form-control"%>
            </div>
            <div class="form-group">
              <%= form.label :age, class:"sr-only" %>
              <%= form.number_field :age, type: 'age', placeholder:"Age...", class:"r-form-1-age form-control"%>
            </div>
            <div class="form-group">
              <%= form.label :country, class:"sr-only" %>
              <%= form.text_field :country, type: 'country', placeholder:"Country...", class:"r-form-1-country form-control"%>
            </div>
            <div class="form-group">
              <%= form.label :gender, class:"sr-only" %>
              <%= form.text_field :gender, type: 'gender', placeholder:"Gender...", class:"r-form-1-gender form-control"%>
            </div>
            <div class="form-group">
              <%= form.label :email, class:"sr-only" %>
              <%= form.email_field :email, type: 'email', placeholder:"Email...", class:"r-form-1-email form-control"%>
            </div>
            <div class="form-group">
              <%= form.label :password, class:"sr-only" %>
              <%= form.password_field :password, placeholder:"Password...",class:"r-form-1-password form-control" %>
            </div>
            <br>
            <div class="submit-field">
              <%= button_tag "Sign up", type: "submit", class: "btn" %>
              <%# form.submit "Login", class: "btn" %>
            </div>
            <%= link_to "Sign in with Facebook", "/auth/facebook" %>
        </div>
      </div>
    </div>
<br><br><br>

app/views/users/edit.html.erb
<h1>Editing User</h1>
  <%= form_for @user do |form| %>
      <div class="row">
        <div class="col-sm-6 col-sm-offset-3 r-form-1-box wow fadeInUp">
          <div class="r-form-1-bottom">
            <p><%= form.file_field :avatar, id:"uploadavatar" %></p>
              <div class="form-group">
                <%= form.label :name, class:"sr-only" %>
                <%= form.text_field :name, type: 'name', placeholder:"Name...", class:"r-form-1-name form-control"%>
              </div>
              <div class="form-group">
                <%= form.label :age, class:"sr-only" %>
                <%= form.number_field :age, type: 'age', placeholder:"Age...", class:"r-form-1-age form-control"%>
              </div>
              <div class="form-group">
                <%= form.label :country, class:"sr-only" %>
                <%= form.text_field :country, type: 'country', placeholder:"Country...", class:"r-form-1-country form-control"%>
              </div>
              <div class="form-group">
                <%= form.label :gender, class:"sr-only" %>
                <%= form.text_field :gender, type: 'gender', placeholder:"Gender...", class:"r-form-1-gender form-control"%>
              </div>
              <div class="form-group">
                <%= form.label :email, class:"sr-only" %>
                <%= form.email_field :email, type: 'email', placeholder:"Email...", class:"r-form-1-email form-control"%>
              </div>
              <div class="form-group">
                <%= form.label :password, class:"sr-only" %>
                <%= form.password_field :password, placeholder:"Password...",class:"r-form-1-password form-control" %>
              </div>
              <br>
              <div class="submit-field">
                <%= button_tag "Update", type: "submit", class: "btn" %>
            </div>
          </div>
        </div>
      </div>
<% end %>
<%= link_to 'Show', @user %>

app/views/users/index.html.erb
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Age</th>
      <th>Country</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.age %></td>
        <td><%= user.country %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <!-- <h2><%= t(".title") %></h2> -->

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

  <% end %>
</div>

app/views/users/show.html.erb
<br>
<% if current_user.avatar.url != nil%>
<%= image_tag(current_user.avatar.thumb.url, :class =>'img-circle') %>
<% end %>
<br><br>


<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @user.age %>
</p>

<p>
  <strong>Country:</strong>
  <%= @user.country %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %>

<br><br>
<h3>Reservations:</h3>
<br>
<table>
  <tr>
    <th>Listing Name</th>
    <th>Check In</th>
    <th>Check Out</th>
    <th>Number Of Guests</th>
    <th>Total Price</th>
    <th>Paid?</th>
    <th></th>
    <th></th>
  </tr>
<% @reservation.each do |reservation| %>
<tr>
  <td><%= link_to reservation.listing.description, reservation.listing %></td>
  <td><%= reservation.check_in.strftime('%d %B %Y') %></td>
  <td><%= reservation.check_out.strftime('%d %B %Y') %></td>
  <td><%= reservation.num_of_guests %></td>
  <td><%= reservation.total_price %></td>
  <td><%= reservation.paid %></td>
    <% if reservation.paid == false %>
  <td><%= link_to "Make Payment", new_reservation_braintree_path(reservation) %></td>
    <% else %>
  <td></td>
    <% end %>
  <td><%= link_to "Cancel Reservation", reservation, method: :delete %></td>
</tr>
<% end %>
</table>

<br>