config/routes.rb
Rails.application.routes.draw do
  get 'images/destroy'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :images, only: [:destroy]
  resources :users, controller: "users" do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "static#index"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  resources :listings do
    resources :reservations, only: [:create]
  end
  resources :reservations, only: [:destroy] do
    resources :braintree, only: [:new, :create]
  end

  get "/my_listings" => "listings#mylisting"
  get '/search', to: 'listings#search', as: 'search'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
  	<meta http-equiv="X-UA-Compatible" content="IE=edge">
  	<meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSS -->
  	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:400,700">

    <title>AirbnbClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB1OJ2LVjPpwrxpiT1qQNEzrdo40juTQDk&libraries=places" type="text/javascript"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script>
  </head>

  <body>
    <nav class="navbar navbar-inverse" role="navigation">
  		<div class="container-fluid" id="navbar">
  			<div class="navbar-header">
  				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#top-navbar-1">
  					<span class="sr-only">Toggle navigation</span>
  					<span class="icon-bar"></span>
  					<span class="icon-bar"></span>
  					<span class="icon-bar"></span>
  				</button>
  				<a class="navbar-brand" href="/">AirBnb Clone</a>
  			</div>
  				<ul class="nav navbar-nav navbar-right">
            <% if signed_in? %>
            <li>
              <%= link_to new_listing_path(current_user) do %>
                Become A Host
              <% end %>
            </li>
            <li>
              <% if current_user.user? %>
                <%= link_to user_path(current_user), id:"navbar-pic" do %>
                  <%= image_tag(current_user.avatar.thumb.url, :class =>'img-circle', :id => 'profilepic') if current_user.avatar.url%> <%= current_user.name %>
                <% end %>
              <% elsif current_user.moderator? %>
                <%= link_to user_path(current_user), id:"navbar-pic" do %>
                <%= image_tag(current_user.avatar.thumb.url, :class =>'img-circle', :id => 'profilepic') if current_user.avatar.url %> Moderator: <%= current_user.name %>
                <% end %>
              <% else %>
                <div class="dropdown">
                  <%= link_to user_path(current_user), id:"navbar-pic" do %>
                    <%= image_tag(current_user.avatar.thumb.url, :class =>'img-circle', :id => 'profilepic') if current_user.avatar.url %> SuperAdmin: <%= current_user.name %>
                  <% end %>
                  <div id="myDropdown" class="dropdown-content">
                    <%= link_to 'View all Users', users_path %>
                    <%= link_to 'View all Listings', listings_path %>
                  </div>
                </div>
              <% end %>
            </li>
            <li>
              <%= link_to sign_out_path, method: :delete do %>
                <span class="glyphicon glyphicon-log-out"></span>  Logout
              <% end %>
            </li>
					  <li><a href="/profile/<%= session[:user_id] %>"></a></li>
              <% else %>
              <li>
                <%= link_to sign_up_path do %>
                  <span class="glyphicon glyphicon-user"></span>  Sign Up
                <% end %>
              </li>
    	        <li>
                <%= link_to sign_in_path do %>
                  <span class="glyphicon glyphicon-log-in"></span>  Login
                <% end %>
              </li>
                <% end %>
  				</ul>
  			</div>
  		</div>
  	</nav>

    <p id="notice"><%= notice %></p>
    <%= yield %>
    <!-- Footer -->
    <footer>
      <div class="container-fluid">
        <div class="row">
          <div class="col-sm-4 footer-about wow fadeInUp">
            <h3>About Us</h3>
            <p>Web Developer From Next Academy</p>
            <p>
                    <a class="scroll-link" href="#about-us">Learn More</a>
                  </p>
                </div>
          <div class="col-sm-5 footer-contact-info wow fadeInDown">
            <h3>Contact Info</h3>
                <p><i class="fa fa-map-marker"></i>Location: Next Academy, Glomac Damansara, TTDI, Kuala Lumpur, Malaysia </p>
                <p><i class="fa fa-phone"></i> Phone: 012-3456789</p>
                <p><i class="fa fa-envelope"></i> Email: <a href="mailto:justin@next.com">justin@next.com</a></p>
                </div>
            <div class="col-sm-3 footer-social wow fadeInUp">
                  <h3>We're Social</h3>
                  <p>
                    <a href="#"><i class="fa fa-facebook"></i></a>
                    <a href="#"><i class="fa fa-twitter"></i></a>
                    <a href="#"><i class="fa fa-instagram"></i></a>
                  </p>
            </div>
          </div>
        <div class="row">
            <div class="col-sm-6 footer-copyright">
                  &copy; AIRBNB CLONE BY JUSTIN
                </div>
            <div class="col-sm-6 footer-menu">
                  <ul>
                    <li><a class="scroll-link" href="#top-content">Top</a></li>
          <li><a class="scroll-link" href="#features">Features</a></li>
          <li><a class="scroll-link" href="#how-it-works">How it works</a></li>
          <li><a href="#">Terms</a></li>
          <li><a href="#">Privacy</a></li>
        </ul>
            </div>
          </div>
      </div>
    </footer>
  </body>
</html>